### ISSUE TITLE
Template from local file?

### ISSUE THREAD

**Issue by dbendy** [drone-plugins/drone-email#11]
Can the email template be read from a local file?  If so, can you please provide an example of that?

**Comment by tboerger** [comment]
You can find the default template at https://github.com/drone-plugins/drone-email/blob/master/template.go#L8-L292

A local file won't work because it would require a volume which is only possible with trusted repositories, but you can use remote files served via http or ftp, just provide the url instead of a template string, than it gets detected

**Comment by tboerger** [comment]
For the upcoming 0.5 you can use local files, https://github.com/drone/drone-go/blob/master/template/template.go#L37 for reference

**Comment by dbendy** [comment]
@tboerger: what about a remote file served via `https`?

**Comment by tboerger** [comment]
> @tboerger: what about a remote file served via https?

That should also work, but there is no option to skip verification if it's served with self-signed certs.
